### ISSUE TITLE
Issue with rgl.spheres and spheres3d

### ISSUE THREAD

**Issue by uwemenzel** [dmurdoch/rgl#289] opened 2023-01-01 17:14 UTC
Hi,
thank you very much for providing the rgl package. 
While many things work perfectly for me, I unfortunately also encountered some issues.
I do not suceed plotting spheres using the package. 
For example, I use the code snippet
   rgl.open()                          # Open a new RGL device
   rgl.bg(color = "white")     # Setup the background color
   rgl.spheres(x, y, z, r = 0.2, color = "grey") 
taken from 
http://www.sthda.com/english/wiki/a-complete-guide-to-3d-visualization-device-system-in-r-r-software-and-data-visualization 

I can open the window and I can change the background to white. But the rgl.spheres command just does not do anything. I also noticed that there is no description of rgl.spheres in the documentation. The same is valid for spheres3d. It just does not plot anything, and no error messages appears. I have updated the package and all dependencies by running install.packages("rgl", dep = TRUE), which worked without problems.
I'm using RStudio 2022.12.0 Build 353 with "R version 4.2.2 (2022-10-31 ucrt)" on Windows10. 
AMD Ryzen 7 5700U with Radeon Graphics
64-bit operating system, x64-based processor
16,0 GB (15,4 GB usable)
rgl version ‘0.110.2’ 
Any help is appreciated!

**Comment by dmurdoch** [comment] 2023-01-01 19:26
You shouldn't be using the obsolete functions `rgl.open`, `rgl.bg` or `rgl.spheres`.  The web page you link to is quite out of date, but I don't see a way to leave a comment for the author.  If you know one, could you please pass on this message to them?

The supported way to do those steps is to run

```
open3d() # Open a new RGL device
# bg3d(color = "white") # white is the default, you don't need this
spheres3d(x, y, z, r = 0.2, color = "grey")
```
You can read more about the changes here:  https://github.com/dmurdoch/rgl/blob/deprecated/vignettes/deprecation.Rmd .

**Comment by uwemenzel** [comment] 2023-01-02 12:09
> open3d() # Open a new RGL device
> spheres3d(x, y, z, r = 0.2, color = "grey")

Thanks a lot, Duncan, for the quick answer.
However, even with the code above (and specifying x,y,z before), I have the same issue.
(I tried this before, even in the usual Windows R environment in order to exclude that this is an RStudio issue).
I'm really sorry to say that ..

**Comment by dmurdoch** [comment] 2023-01-02 13:34
I think you'll need to show me x, y, and z then so I have  reproducible example.

**Comment by uwemenzel** [comment] 2023-01-02 15:35
Hi,

for example:

library(rgl)
open3d() # Open a new RGL device
x = rnorm(5)
y = 3*rnorm(5,2)
z = 2*rnorm(5,2)
spheres3d(x, y, z, r = 0.2, color = "grey")


Best, Uwe

**Comment by dmurdoch** [comment] 2023-01-02 16:06
That works fine for me.  Please try installing the devel version using

    remotes::install_github("dmurdoch/rgl")

It should appear on CRAN in a week or two.  If that's not enough to fix the issue, it might be a problem specific to your hardware.  As a workaround, you should still be able to use `rglwidget()` to have things display in a browser or the RStudio Viewer window instead.

**Comment by uwemenzel** [comment] 2023-01-03 11:43
Okay,
thanks!!
Best,
Uwe

**Comment by dmurdoch** [comment] 2023-01-27 17:52
I am closing this now, as I couldn't reproduce it.  If it is still happening or starts again, please comment here and reopen it.

**Closed as completed by dmurdoch** 2023-01-27 17:52 UTC

**Comment by uwemenzel** [comment] 2023-01-28 09:47
Okay, thanks!
