### ISSUE TITLE
rgl plot displays incorrectly once sent to rglwidget

### ISSUE THREAD

**Issue by blex-max** [dmurdoch/rgl#169] opened 2022-01-16 23:23 UTC
I'm trying to make some nice rgl 3d scatterplots I can include in an HTML document. They look fine when I display them in the rgl pane in RStudio - here: [good output](https://i.stack.imgur.com/VAguT.png) But as soon as they're captured with scene3d() things go wrong. If I call the object assigned output from rglwidget(), all the colour is gone from the spheres and the planes don't appear, instead I get this: [bad output](https://i.stack.imgur.com/gpmsy.jpg) I'm on R 4.1 and Ubuntu 20.04, and as far as I'm aware I've installed all the dependencies. I've tried my best with the doc etc. but I'm finding it a bit difficult to parse. Thanks!

code to reproduce:

```
library(rgl)
foo <- cbind(runif(20, -1, 1), runif(20, -1, 1), runif(20, -1, 1), c(rep(1,10), rep(2,10)))

plot3d(x = foo[,1], 
       y = foo[,2], 
       z = foo[,3],
       xlab = '',
       ylab = '',
       zlab = '',
       col = ifelse(foo[,4] == 1, '#636EFA', '#EF553B'),
       type = 's',
       size = 2,
       xlim = c(floor(min(foo[,1])), ceiling(max(foo[,1]))),
       ylim = c(floor(min(foo[,2])), ceiling(max(foo[,2]))),
       zlim = c(floor(min(foo[,3])), ceiling(max(foo[,3]))),
       axes = F)

axes3d(fig, edges = c('x-', 'y-', 'z-+'), labels = TRUE, tick = TRUE, nticks = 5, 
       expand = 1.03, floating = F)
title3d(xlab = 'PC1', ylab = 'PC2', level = 5, floating = F)
title3d(zlab = 'PC3', line = 5, level = -20, floating = F)


planes3d(1,0,0,-ceiling(max(foo[,1])), color = "#333777", alpha = 0.6, 
         emission="#333777", specular='black', shininess=5, floating = F) #x
planes3d(0,1,0,-ceiling(max(foo[,2])), color = "#333777", alpha = 0.6, 
         emission="#333777", specular='black', shininess=5, floating = F) #y
planes3d(0,0,1,-floor(min(foo[,3])), color = "#333777", alpha = 0.6, 
         emission="#333777", specular='black', shininess=5, floating = F) #z


widge <- rglwidget()
widge
```

  [1]: https://i.stack.imgur.com/VAguT.png
  [2]: https://i.stack.imgur.com/gpmsy.jpg

**Comment by dmurdoch** [comment] 2022-01-17 11:52
Thanks for the report.  I can confirm the bug:  I'll see if I can track it down.

**Comment by dmurdoch** [comment] 2022-01-17 11:56
Correction:  the planes disappear, but I am not seeing a problem with the spheres.

**Comment by dmurdoch** [comment] 2022-01-17 12:14
The issue with the planes appears to be related to setting the `xlim`, `ylim` and `zlim` values in the `plot3d` call.

**Comment by blex-max** [comment] 2022-01-17 12:21
Interesting, so the spheres don't appear black for you? Thanks for looking into it.

**Comment by dmurdoch** [comment] 2022-01-17 15:08
No, the spheres look fine.

I'm pretty sure there are bugs in plane drawing, but I'm also not sure that what you did should work.  

The issue is this:  when you draw planes, rgl will only draw the part of the plane that intersects with the current bounding box of the data.  By using `xlim`, `ylim` and `zlim`, that becomes complicated:  in order to implement clipping of the data but not of the titles, labels, etc, rgl creates a separate region within the plot to hold the data, and does clipping there.  

I think when you are drawing the planes, they aren't in that region, so I'm not sure what bounding box would be used to determine where they are drawn, but I think it is one where the planes are exactly on the boundary of the clipping region, and then rounding error would determine whether they are shown or not.  That could explain the inconsistency between the two displays, but I've also found some bugs in the WebGL code that might explain it.

So for now my advice would be not to use `planes3d` in the way you're using it.  If you want to draw planes on the boundary of the range of points, then you're probably safer to use `quads3d` to draw squares.  They won't resize when you change the plot, but it should be possible to draw them.  

An alternative would be to draw some points outside the region where the planes should appear to make sure rgl sees a bigger bounding box.  You can set `alpha` to a very small value and the points will be invislble.  (I forget if `alpha = 0` would work, or would cull the points.)

I'll post here again after I'm sure about all of this, and have committed any necessary fixes.

**Closed as completed** 2022-01-18 17:17 UTC

**Comment by dmurdoch** [comment] 2022-01-18 17:20
I have closed this now.  I think the display of planes in `rglwidget()` was as designed, they shouldn't have appeared in the main display.  The loss of color is almost certainly a bug specific to your system, i.e. not in `rgl`, but in the graphics driver.  To check this, see if the HTML file produced on the bad system shows the same loss of color when viewed on a different system.  If it does show the problem, please reopen this issue and attach code and output that illustrates it.
