### ISSUE TITLE
error in rendering points in Rmarkdown

### ISSUE THREAD

**Issue by AleBitetto** [dmurdoch/rgl#61] opened 2021-03-19 02:22 UTC
Hi,

I have the following problem:
https://stackoverflow.com/questions/66694353/r-rgl-layout3d-breaks-playwidget-in-rmarkdown

is it a bug or am I missing something?

If you want, you can replace the `fun_layout3D` in the example with the following one in order to reproduce the "square" points error, aside the slider problem if move the `fun_playwidget` cell after the layout3D one. Someone suggested the `reuse=FALSE` but it's still not working.

Thanks

```
fun_layout3D_points = function(){
  clear3d()
  mat <- matrix(1:2, ncol = 2)
  layout3d(mat, height = c(2,2), widths = c(2,2), sharedMouse = T)
  data = matrix(sample.int(100, 81), ncol = 3)
  next3d()
  plot3d(xyz.coords(data), col = "blue", type = "p", size = 30)
  next3d()
  plot3d(xyz.coords(data), col = "red", type = "p", size = 30)
}
```

I have the same problem even if I use `knitr::knit_hooks$set(webgl = hook_webgl)` and keep `webgl=TRUE` in the cell options

**Comment by dmurdoch** [comment] 2021-03-19 08:40
Please post a complete reproducible example, and give the versions of R and rgl that you're using.

**Comment by AleBitetto** [comment] 2021-03-19 08:58
Here it is. This produces both issues: point are rendered as squares and the slider doesn't move.

```
---
title: Test
output:
  html_document
---


```{r, echo=FALSE, include=FALSE, fig.height = 13, fig.width = 13}
suppressMessages(suppressWarnings(library(rgl)))
options(rgl.useNULL = TRUE) # Suppress the separate window.

# define function
fun_playwidget = function(){

clear3d()    
setosa <- with(subset(iris, Species == "setosa"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
                  col=as.numeric(Species),
                  radius = 0.211))
versicolor <- with(subset(iris, Species == "versicolor"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
               col=as.numeric(Species),
               radius = 0.211))
out = rglwidget() %>%
playwidget(start = 0, stop = 1, interval = 1,
       subsetControl(1, subsets = list(
                 Setosa = setosa,
                 Versicolor = versicolor
                 )))

return(out)
}

fun_layout3D = function(){
clear3d()
  mat <- matrix(1:2, ncol = 2)
  layout3d(mat, height = c(2,2), widths = c(2,2), sharedMouse = T)
  data = matrix(sample.int(100, 81), ncol = 3)
  next3d()
  plot3d(xyz.coords(data), col = "blue", type = "p", size = 30)
  next3d()
  plot3d(xyz.coords(data), col = "red", type = "p", size = 30)
  rglwidget()
}
\```

# layout3d
```{r, echo=FALSE, include=TRUE, fig.height = 5, fig.width = 5}
fun_layout3D()
\```

# playwidget
```{r, echo=FALSE, include=TRUE, fig.height = 5, fig.width = 5}
fun_playwidget()
\```
```
(sorry for the last three leading backslashes, I didn't find a better way to prevent markdown commands)


And here's the session info

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
 [1] compiler  parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1       purrr_0.3.4         readr_1.4.0         tidyr_1.1.2         tibble_3.1.0        tidyverse_1.3.0     dplyr_1.0.3         data.table_1.12.8  
 [9] parallelMap_1.5.0   PKPDmisc_3.0.0      rgl_0.100.54        LatticeDesign_2.0-4 DescTools_0.99.34   uwot_0.1.10         rpca_0.2.3          mlrMBO_1.1.5       
[17] smoof_1.5.1         checkmate_1.9.4     BBmisc_1.11         mlr_2.14.0          ParamHelpers_1.12   magick_2.1          parallelDist_0.2.4  clusterCrit_1.2.8  
[25] randtoolbox_1.30.1  rngWELL_0.10-6      gridExtra_2.3       gtable_0.3.0        gganimate_1.0.7     lubridate_1.7.10    Hmisc_4.4-0         ggplot2_3.3.0      
[33] Formula_1.2-3       survival_3.1-12     lattice_0.20-38     reshape_0.8.8       optimx_2020-4.2     lme4_1.1-25         Matrix_1.2-18       ppcor_1.1          
[41] MASS_7.3-51.5       stringr_1.4.0       readxl_1.3.1       

loaded via a namespace (and not attached):
  [1] backports_1.1.5         fastmatch_1.1-0         plyr_1.8.6              lazyeval_0.2.2          splines_3.6.3           crosstalk_1.0.0        
  [7] tfruns_1.4              digest_0.6.27           htmltools_0.5.1.1       fansi_0.4.2             magrittr_2.0.1          cluster_2.1.0          
 [13] modelr_0.1.6            RcppParallel_5.0.2      prettyunits_1.1.1       colorspace_1.4-1        rvest_0.3.5             rappdirs_0.3.3         
 [19] ggrepel_0.8.2           haven_2.3.1             xfun_0.22               crayon_1.4.1            jsonlite_1.7.2          zeallot_0.1.0          
 [25] glue_1.4.2              webshot_0.5.2           scales_1.0.0            mvtnorm_1.0-11          DBI_1.0.0               miniUI_0.1.1.1         
 [31] Rcpp_1.0.6              viridisLite_0.3.0       xtable_1.8-4            progress_1.2.2          htmlTable_1.13.2        reticulate_1.18        
 [37] foreign_0.8-75          htmlwidgets_1.5.1       httr_1.4.2              RColorBrewer_1.1-2      acepack_1.4.1           ellipsis_0.3.1         
 [43] pkgconfig_2.0.3         farver_2.0.3            dbplyr_2.1.0            nnet_7.3-12             utf8_1.2.1              RJSONIO_1.3-1.2        
 [49] tidyselect_1.1.0        rlang_0.4.10            manipulateWidget_0.10.1 later_1.0.0             munsell_0.5.0           cellranger_1.1.0       
 [55] tools_3.6.3             cli_2.3.1               generics_0.1.0          broom_0.5.2             evaluate_0.14           fastmap_1.0.1          
 [61] yaml_2.2.1              fs_1.3.1                knitr_1.31              nlme_3.1-144            whisker_0.4             mime_0.10              
 [67] xml2_1.3.2              rstudioapi_0.13         plotly_4.9.0            ggsignif_0.6.0          reprex_0.3.0            lhs_1.0.1              
 [73] statmod_1.4.34          tweenr_1.0.1            stringi_1.5.3           plot3D_1.3              tensorflow_2.2.0        keras_2.3.0.0.9000     
 [79] nloptr_1.2.2.1          vctrs_0.3.6             pillar_1.5.1            lifecycle_1.0.0         RcppAnnoy_0.0.18        httpuv_1.5.2           
 [85] R6_2.5.0                latticeExtra_0.6-28     promises_1.1.0          codetools_0.2-16        boot_1.3-24             assertthat_0.2.1       
 [91] withr_2.4.1             expm_0.999-4            hms_1.0.0               rpart_4.1-15            minqa_1.2.4             rmarkdown_2.7          
 [97] misc3d_0.8-4            mco_1.0-15.1            ggpubr_0.2.5            numDeriv_2016.8-1.1     shiny_1.6.0             base64enc_0.1-3
```

**Comment by dmurdoch** [comment] 2021-03-19 09:19
You should use `open3d()` rather than `clear3d()`:  the latter doesn't clear the subscene layout.

You should also use `reuse=FALSE` in the `rglwidget()` calls.  This looks like a bug in rendering, and `reuse=FALSE` works around it.

I'm not sure what's going on with the square vs round points:  I'll investigate that.

Finally, you should update to a current version of `rgl`:  yours is pretty old (but the bugs with reuse and square points are still there).

**Comment by AleBitetto** [comment] 2021-03-19 11:15
Thanks, that fixed the slider problem. I'll wait for the square points problem to be fixed when you have time.

**Comment by dmurdoch** [comment] 2021-03-20 14:04
The round points issue is now fixed:  if you set material property `point_antialias` to TRUE, you'll get round points in `rglwidget()` displays.  (This is supposed to be the behaviour in R as well, but it is unreliably implemented by graphics hardware and drivers.)

**Closed as completed** 2021-03-20 15:30 UTC

**Comment by dmurdoch** [comment] 2021-03-20 15:38
This version of the script works in the latest devel version:

---
title: Test
output:
  html_document
---


```{r, echo=FALSE, include=FALSE, fig.height = 13, fig.width = 13}
suppressMessages(suppressWarnings(library(rgl)))
options(rgl.useNULL = TRUE) # Suppress the separate window.

# define function
fun_playwidget = function(){

open3d()    
setosa <- with(subset(iris, Species == "setosa"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
                  col=as.numeric(Species),
                  radius = 0.211))
versicolor <- with(subset(iris, Species == "versicolor"), 
     spheres3d(Sepal.Length, Sepal.Width, Petal.Length, 
               col=as.numeric(Species),
               radius = 0.211))
out = rglwidget() %>%
playwidget(start = 0, stop = 1, interval = 1,
       subsetControl(1, subsets = list(
                 Setosa = setosa,
                 Versicolor = versicolor
                 )))

return(out)
}

fun_layout3D = function(){
open3d()
  mat <- matrix(1:2, ncol = 2)
  layout3d(mat, height = c(2,2), widths = c(2,2), sharedMouse = T)
  data = matrix(sample.int(100, 81), ncol = 3)
  next3d()
  plot3d(xyz.coords(data), col = "blue", type = "p", size = 30, point_antialias = TRUE)
  next3d()
  plot3d(xyz.coords(data), col = "red", type = "p", size = 30, point_antialias = TRUE)
  rglwidget()
}
\```

# layout3d
```{r, echo=FALSE, include=TRUE, fig.height = 5, fig.width = 5}
fun_layout3D()
\```

# playwidget
```{r, echo=FALSE, include=TRUE, fig.height = 5, fig.width = 5}
fun_playwidget()
\```

**Comment by AleBitetto** [comment] 2021-03-20 22:03
Thanks, it works perfectly!
